name: Generate Impact and UTCs
on:
  pull_request:
    branches:
      - '*'

jobs:
  generate_impact_utcs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: execute generate_utcs.py script
        id: generate_utcs
        run: |
          output=$(python .github/workflows/generate_utcs.py)
          output="${output//'%'/'%25'}"
          output="${output//$'\n'/'%0A'}"
          output="${output//$'\r'/'%0D'}"
          echo "::set-output name=utcs::$output"

      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            ${{ steps.generate_utcs.outputs.utcs }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          allow-repeats: false